#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

HOOK="pre-commit"
readonly HOOK

for i in $(find `dirname $0`/*/* -name $HOOK); 
do 
    $i "$@"
done