general {
	lock_cmd = pidof hyprlock || hyprlock
	before_sleep_cmd = loginctl lock-session
	after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
	# lock screen and turn off screen at 15 min
	timeout = 900
	on-timeout = loginctl lock-session && hyprctl dispatch dpms off
	on-resume = hyprctl dispatch dpms on
}

listener {
	# suspend system after 30 min
	timeout = 1800
	on-timeout = systemctl suspend
}
