################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=DP-6,preferred,0x0,auto,transform,3
monitor=DP-5,preferred,1080x0,auto

workspace = 1,monitor:DP-6
workspace = 2,monitor:DP-6
workspace = 3,monitor:DP-6

workspace = 4,monitor:DP-5,default:true
workspace = 5,monitor:DP-5
workspace = 6,monitor:DP-5
workspace = 7,monitor:DP-5
workspace = name:scratch,monitor:DP-5,s[true]
workspace = name:magic,monitor:DP-5,s[true]
workspace = name:steam,monitor:DP-5,s[true]
cursor:default_monitor=DP-5

workspace =  8,monitor:DP-4
workspace =  9,monitor:DP-4
workspace = 10,monitor:DP-4

