##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
	# Ignore maximize requests from all apps. You'll probably like this.
	name = suppress-maximize-events
	match:class = .*

	suppress_event = maximize
}

windowrule {
	# Fix some dragging issues with XWayland
	name = fix-xwayland-drags
	match:class = ^$
	match:title = ^$
	match:xwayland = true
	match:float = true
	match:fullscreen = false
	match:pin = false

	no_focus = true
}

# Hyprland-run windowrule
windowrule {
	name = move-hyprland-run

	match:class = hyprland-run

	move = 20 monitor_h-120
	float = yes
}

windowrule {
	name = opacity-high
	match:title = btop|.*YouTube.*|.*Hulu.*|.*[pP]aramount.*
	opacity = 1 override 1 override
}

# special:scratch section
windowrule {
	name = special:scratch
	match:title = btop|scratch-terminal
	workspace = special:scratch silent
	opacity = 1 override 1 override
	monitor = DP-5
}

# secial:magic
windowrule {
	name = special:magic
	match:class = spotify
	workspace = special:magic silent
	opacity = 1 override 1 override
	monitor = DP-5
}

# special:steam
windowrule {
	name = special:steam
	match:class = steam
	workspace = 7 silent
	monitor = DP-5
	opacity = 1 override 1 override
}
