#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

exec pwsh -ExecutionPolicy ByPass -Command "$(dirname "$0")/pre-commit.ps1 $@ -GitDir $(git rev-parse --show-toplevel)"