#!/usr/bin/env pwsh

parm( [switch]$Help )

$ErrorActionPreference = 'Stop'

if ($Help.IsPresent) {
	Write-Host @'
	Creates a new branch from the current branch and current commit

	Usage: git branchoff <branch name>
'@
	exit 0
}

if (!$args) { Write-Error "An existing local branch name is required" }

New-Variable -Name BranchName -Value $args[0] -Scope Script -Option Readonly
New-Variable -Name Pattern -Value "refs\/heads\/" -Scope Script

git fetch --no-tags --quiet

if ((git show-ref --heads --quiet | % { $_ -split $Pattern, 2 | Select -Index 1 }) -match $BranchName) {
	Write-Error "Local branch already exists"
}

if ((git ls-remote --heads | % { $_ -split $Pattern, 2 | Select -Index 1 }) -match $BranchName) {
	Write-Error "Remote branch already exists"
}

git checkout -b $BranchName
git commit -m "Initial $BranchName branch point" --allow-empty --no-verify

