#!/usr/bin/env pwsh

# mac target: /usr/local/bin
# win target: ~./.git-commands

# creates a new branch point from current branch

if ($null -eq $args[0]) {
    Write-Host 'No branch name given'
    exit 0
}

if ($null -ne (git show-ref --heads | sls $args[0])) {
    Write-Host 'Branch already exists'
    exit 0
}

git checkout -b $args[0]
git commit -m "Initial $($args[0]) branch point" --allow-empty --no-verify